<?php
declare(strict_types=1);
namespace Mayuan;
final class Application {
 private Storage $store;
 public function __construct(\PDO $db,private string $mode){$this->store=new Storage($db);if($this->store->get('content')===null)$this->store->transaction(function(){$c=Content::validate(json_decode(file_get_contents(__DIR__.'/../resources/content.json'),true,512,JSON_THROW_ON_ERROR));$this->store->put('content',['draft'=>$c,'published'=>$c,'revision'=>1,'revisions'=>[['version'=>$c['contentVersion'],'publishedAt'=>self::now()]],'versions'=>[$c['contentVersion']=>$c]]);});}
 private static function now():int{return (int)floor(microtime(true)*1000);}
 public static function blank():array{return ['revision'=>0,'nodes'=>[],'attempts'=>[],'recalls'=>[],'historicalAnswers'=>[],'favorites'=>[],'notes'=>[],'resume'=>['view'=>'map','nodeId'=>null],'sync'=>['status'=>'unconfigured','pending'=>0]];}
 public function dispatch(string $method,string $path,array $body,?array $user):array{
 if($method==='GET'&&$path==='/session')return ['mode'=>$this->mode==='development'?'development':'guanlan','user'=>$user,'integration'=>GuanlanAdapter::status()];
 if($method==='POST'&&$path==='/dev-login'){if($this->mode!=='development')throw new ApiError(403,'development_disabled','开发账号已禁用');$account=$body['account']??'';if(!in_array($account,['learner','second','admin'],true))throw new ApiError(422,'invalid_account','开发账号无效');return ['user'=>['id'=>'dev:'.$account,'name'=>['learner'=>'开发学习者','second'=>'第二开发学习者','admin'=>'开发管理员'][$account],'role'=>$account==='admin'?'admin':'learner']];}
 if($method==='GET'&&$path==='/content')return Content::publicContent($this->store->get('content')['published']);
 if(!$user||($this->mode!=='development'&&!str_starts_with($user['id'],'guanlan:')))throw new ApiError(401,'unauthenticated','请先登录');
 if($method==='POST'&&$path==='/logout')return ['loggedOut'=>true];
 $key='user:'.hash('sha256',$user['id']);$this->store->put($key.':identity',$user['id']);
 if($method==='GET'&&$path==='/state')return $this->state($key);
 if($method==='GET'&&$path==='/export')return ['version'=>2,'exportedAt'=>self::now(),'contentVersion'=>$this->store->get('content')['published']['contentVersion'],'state'=>$this->state($key)];
 if(str_starts_with($path,'/admin/')){if(($user['role']??'')!=='admin')throw new ApiError(403,'forbidden','需要管理员权限');return $this->admin($method,$path,$body);}
 if($method==='POST'&&$path==='/import')return $this->store->transaction(function()use($key,$body){if(($body['confirm']??null)!==true)throw new ApiError(422,'confirmation_required','请预览并确认导入归属');$old=$this->state($key);$incoming=ImportProgress::validate($body['progress']??null,$this->store->get('content')['published']);$fingerprint=hash('sha256',json_encode($body['progress']));$imports=$this->store->get($key.':imports',[]);if(isset($imports[$fingerprint]))return $old;foreach($incoming['nodes'] as $id=>$node){$existing=$old['nodes'][$id]??self::node();$existing['visited']=$existing['visited']||$node['visited'];if(($node['masteryUpdatedAt']>$existing['masteryUpdatedAt']||($node['masteryUpdatedAt']===$existing['masteryUpdatedAt']&&$existing['mastery']==='unlearned'&&$node['mastery']!=='unlearned'))){$existing['mastery']=$node['mastery'];$existing['masteryUpdatedAt']=$node['masteryUpdatedAt'];}$existing['updatedAt']=self::now();$old['nodes'][$id]=$existing;}foreach(['favorites','notes','recalls'] as $kind){foreach($incoming[$kind] as $v){$id=is_string($v)?$v:$v['id'];$exists=false;foreach($old[$kind] as $x)if((is_string($x)?$x:$x['id'])===$id)$exists=true;if(!$exists)$old[$kind][]=$v;}}foreach($incoming['historicalAnswers'] as $answer){if(in_array($answer['id'],array_column($old['historicalAnswers'],'id'),true))continue;$answer['verified']=false;$answer['source']='import';$answer['importId']=$fingerprint;$old['historicalAnswers'][]=$answer;}$imports[$fingerprint]=true;$this->store->put($key.':imports',$imports);return $this->save($key,$old);});
 if($method==='POST'&&in_array($path,['/events','/attempts'],true))return $this->store->transaction(function()use($key,$path,$body){$id=$path==='/events'?($body['id']??null):($body['eventId']??null);self::identifier($id);$eventKey=$key.':event:'.hash('sha256',$id);$fingerprint=hash('sha256',self::canonical($body));$previous=$this->store->get($eventKey);if($previous){if($previous['hash']!==$fingerprint)throw new ApiError(409,'event_id_reused','事件编号已用于不同内容');return $previous['response'];}$s=$this->state($key);if(isset($body['baseRevision'])&&(!is_int($body['baseRevision'])||$body['baseRevision']!==$s['revision']))throw new ApiError(409,'revision_conflict','进度已更新，请刷新后重新确认操作');$c=$this->store->get('content')['published'];if($path==='/attempts'){$q=null;foreach($c['exercises'] as $v)if($v['id']===($body['exerciseId']??null))$q=$v;if(!$q||!is_int($body['chosen']??null)||$body['chosen']<0||$body['chosen']>=count($q['options'])||!is_string($body['reason']??null)||strlen($body['reason'])>3000)throw new ApiError(422,'invalid_attempt','练习提交无效');$correct=$body['chosen']===$q['answer'];$s['attempts'][]=['id'=>$id,'exerciseId'=>$q['id'],'chosen'=>$body['chosen'],'reason'=>$body['reason'],'correct'=>$correct,'answer'=>$q['answer'],'explanation'=>$q['explanation'],'contentVersion'=>$c['contentVersion'],'nodes'=>$q['nodes'],'at'=>self::now(),'verified'=>true];foreach($q['nodes'] as $n){$s['nodes'][$n]=$s['nodes'][$n]??self::node();$s['nodes'][$n]['visited']=true;$s['nodes'][$n]['updatedAt']=self::now();}$result=['correct'=>$correct,'answer'=>$q['answer'],'explanation'=>$q['explanation'],'state'=>$this->save($key,$s)];}else{$this->apply($s,$body,$c);$result=$this->save($key,$s);}$this->store->put($eventKey,['hash'=>$fingerprint,'response'=>$result]);return $result;});
 throw new ApiError(404,'not_found','接口不存在');
 }
 public static function identifier(mixed $id):void{if(!is_string($id)||!preg_match('/^[a-zA-Z0-9:_-]{1,100}$/',$id)||in_array($id,['__proto__','constructor','prototype']))throw new ApiError(422,'invalid_id','对象或事件编号无效');}
 public static function node():array{return ['visited'=>false,'mastery'=>'unlearned','masteryUpdatedAt'=>0,'updatedAt'=>0];}
 private static function canonical(array $v):string{$sort=function(&$a)use(&$sort){if(is_array($a)){if(!array_is_list($a))ksort($a);foreach($a as &$x)$sort($x);}};$sort($v);return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);}
 private function state(string $key):array{$s=$this->store->get($key,self::blank());$outbox=$this->store->get($key.':outbox',[]);$s['sync']['pending']=count(array_filter($outbox,fn($e)=>!in_array($e['status'],['sent','superseded'],true)));if(GuanlanAdapter::status()['configured'])$s['sync']['status']=$s['sync']['pending']?'pending':'synced';$s['summary']=['visited'=>count(array_filter($s['nodes'],fn($n)=>$n['visited'])),'mastered'=>count(array_filter($s['nodes'],fn($n)=>$n['mastery']==='mastered')),'attempts'=>count($s['attempts']),'correct'=>count(array_filter($s['attempts'],fn($a)=>$a['correct'])),'due'=>self::due($s['recalls'])];return $s;}
 private static function due(array $recalls):int{$latest=[];foreach($recalls as $r)if(!isset($latest[$r['nodeId']])||$r['at']>=$latest[$r['nodeId']]['at'])$latest[$r['nodeId']]=$r;return count(array_filter($latest,fn($r)=>$r['dueAt']<=self::now()));} private function save(string $key,array $s):array{$s['revision']++;$s['updatedAt']=self::now();$outbox=$this->store->get($key.':outbox',[]);$outbox[]=['eventId'=>'mayuan:'.substr(hash('sha256',$key),0,32).':'.$s['revision'],'revision'=>$s['revision'],'status'=>'pending','retries'=>0,'nextAttemptAt'=>self::now(),'payload'=>['schemaVersion'=>1,'eventId'=>'mayuan:'.substr(hash('sha256',$key),0,32).':'.$s['revision'],'revision'=>$s['revision'],'subject'=>$this->store->get($key.':identity'),'contentVersion'=>$this->store->get('content')['published']['contentVersion'],'generatedAt'=>gmdate('c'),'visitedConceptCount'=>count(array_filter($s['nodes'],fn($n)=>$n['visited'])),'selfAssessedMasteredCount'=>count(array_filter($s['nodes'],fn($n)=>$n['mastery']==='mastered')),'practiceAttemptCount'=>count($s['attempts']),'practiceCorrectCount'=>count(array_filter($s['attempts'],fn($a)=>$a['correct'])),'dueReviewCount'=>self::due($s['recalls']),'lastActivityAt'=>gmdate('c'),'resumeTarget'=>$s['resume']]];$s['sync']=['status'=>GuanlanAdapter::status()['configured']?'pending':'unconfigured','pending'=>count(array_filter($outbox,fn($e)=>$e['status']!=='sent'))];$this->store->put($key.':outbox',$outbox);$this->store->put($key,$s);return $this->state($key);}
 private function apply(array &$s,array $b,array $c):void{$p=$b['payload']??null;if(!is_array($p))throw new ApiError(422,'invalid_event','事件内容无效');$type=$b['type']??null;$n=$p['nodeId']??null;if($type!=='resume'||$n!==null){self::identifier($n);if(!in_array($n,array_column($c['nodes'],'id'),true))throw new ApiError(422,'invalid_node','知识点不存在');}$t=self::now();$entry=$n?($s['nodes'][$n]??self::node()):null;
 switch($type){case 'visit':$entry['visited']=true;$entry['updatedAt']=$t;$s['nodes'][$n]=$entry;break;case 'mastery':if(!in_array($p['mastery']??null,['unlearned','fuzzy','mastered'],true))throw new ApiError(422,'invalid_mastery','自评无效');$entry['mastery']=$p['mastery'];$entry['masteryUpdatedAt']=$t;$entry['updatedAt']=$t;$s['nodes'][$n]=$entry;break;case 'favorite':if(!is_bool($p['favorited']??null))throw new ApiError(422,'invalid_favorite','收藏状态无效');$s['favorites']=array_values(array_filter($s['favorites'],fn($id)=>$id!==$n));if($p['favorited'])$s['favorites'][]=$n;break;case 'note':self::identifier($p['id']??null);if(!is_string($p['content']??null)||strlen($p['content'])>15000)throw new ApiError(422,'invalid_note','笔记文本无效');$s['notes']=array_values(array_filter($s['notes'],fn($note)=>$note['id']!==$p['id']));if(trim($p['content'])!=='')$s['notes'][]=['id'=>$p['id'],'nodeId'=>$n,'content'=>$p['content'],'updatedAt'=>$t];break;case 'recall':if(!in_array($p['rating']??null,['again','hard','good'],true)||!is_string($p['mode']??null)||strlen($p['mode'])>60)throw new ApiError(422,'invalid_recall','回忆自评无效');$s['recalls'][]=['id'=>$b['id'],'nodeId'=>$n,'rating'=>$p['rating'],'mode'=>$p['mode'],'at'=>$t,'dueAt'=>$t+['again'=>600000,'hard'=>86400000,'good'=>259200000][$p['rating']]];break;case 'resume':if(!in_array($p['view']??null,['map','stars','compare','lab','recall','quiz','notebook','overview','admin'],true))throw new ApiError(422,'invalid_view','视图无效');$s['resume']=['view'=>$p['view'],'nodeId'=>$n];break;default:throw new ApiError(422,'invalid_event','不支持的事件');}}
 private function admin(string $method,string $path,array $b):array{if($method==='GET'&&$path==='/admin/content'){$c=$this->store->get('content');unset($c['versions']);return $c;}return $this->store->transaction(function()use($method,$path,$b){$c=$this->store->get('content');if($method==='PUT'&&$path==='/admin/content'){if(($b['baseRevision']??null)!==$c['revision'])throw new ApiError(409,'revision_conflict','草稿版本已更新');$c['draft']=Content::validate($b['content']??null);$c['revision']++;}elseif($method==='POST'&&$path==='/admin/publish'){if(($b['revision']??null)!==$c['revision'])throw new ApiError(409,'revision_conflict','请重新确认草稿');$c['published']=$c['draft'];$c['published']['contentVersion']='mayuan-published-'.$c['revision'].'-'.self::now();$c['draft']=$c['published'];$version=$c['published']['contentVersion'];$c['versions'][$version]=$c['published'];$c['revisions'][]=['version'=>$version,'publishedAt'=>self::now()];$c['revision']++;}elseif($method==='POST'&&$path==='/admin/rollback'){if(!is_string($b['version']??null)||!isset($c['versions'][$b['version']]))throw new ApiError(422,'invalid_version','历史版本不存在');$c['published']=$c['versions'][$b['version']];$c['draft']=$c['published'];$c['revision']++;}else throw new ApiError(404,'not_found','接口不存在');$this->store->put('content',$c);unset($c['versions']);return $c;});}
}
