<?php
declare(strict_types=1);
namespace Mayuan;
final class HyperfController {
 public function __construct(private \Hyperf\HttpServer\Contract\RequestInterface $request,private \Hyperf\HttpServer\Contract\ResponseInterface $response,private \Hyperf\Contract\SessionInterface $session){}
 public function handle(string $path):\Psr\Http\Message\ResponseInterface{
 try{$mode=getenv('MAYUAN_MODE')==='development'?'development':'guanlan';$method=$this->request->getMethod();if($method!=='GET'){if(!in_array($this->request->getHeaderLine('Origin'),array_filter(explode(',',getenv('MAYUAN_ORIGINS')?:'')),true))throw new ApiError(403,'origin_rejected','请求来源未获授权');if(!str_starts_with(strtolower($this->request->getHeaderLine('Content-Type')),'application/json'))throw new ApiError(415,'json_required','请求必须为 JSON');}$dsn=getenv('MAYUAN_DB_DSN')?:'';if(!str_starts_with($dsn,'mysql:'))throw new ApiError(503,'database_unconfigured','生产 PDO MySQL 未配置');$raw=(string)$this->request->getBody();if(strlen($raw)>2097152)throw new ApiError(413,'body_too_large','请求过大');try{$body=$raw===''?[]:json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(\Throwable){throw new ApiError(400,'invalid_json','JSON 格式无效');}if(!is_array($body)||(array_is_list($body)&&$body!==[]))throw new ApiError(400,'invalid_json','请求必须为对象');$user=$this->session->get('user');if($mode!=='development'&&$user&&!str_starts_with($user['id'],'guanlan:')){$this->session->clear();$user=null;}if($user&&str_starts_with($user['id'],'guanlan:')){try{$user=(new GuanlanAdapter())->verifyToken($this->session->get('guanlanToken',''));}catch(\Throwable){$this->session->clear();throw new ApiError(401,'session_expired','观澜身份失效');}}(new RequestGuard())->principal('/'.$path,$user,$this->request->getHeaderLine('X-Mayuan-User'));$app=new Application(new \PDO($dsn,getenv('MAYUAN_DB_USER')?:null,getenv('MAYUAN_DB_PASSWORD')?:null),$mode);if($method==='POST'&&$path==='guanlan/validate'){$user=(new GuanlanAdapter())->verifyToken((string)($body['token']??''));$this->session->migrate(true);$this->session->set('user',$user);$this->session->set('guanlanToken',$body['token']);$data=['user'=>$user];}else $data=$app->dispatch($method,'/'.$path,$body,$user);if($method==='POST'&&$path==='dev-login'){$this->session->migrate(true);$this->session->set('user',$data['user']);}if($method==='POST'&&$path==='logout')$this->session->clear();$data=HttpKernel::objects($data);return $this->response->json(['data'=>$data])->withHeader('Cache-Control','no-store');}catch(ApiError $e){return $this->response->json(['error'=>['code'=>$e->errorCode,'message'=>$e->getMessage()]])->withStatus($e->status);}catch(\Throwable){return $this->response->json(['error'=>['code'=>'internal_error','message'=>'服务暂时不可用']])->withStatus(500);}
 }
}
