<?php
declare(strict_types=1);
namespace Mayuan;
final class GuanlanAdapter {
 public static function status():array{$ready=getenv('GUANLAN_SUMMARY_PROTOCOL')==='mayuan-summary-v1'&&str_starts_with(getenv('GUANLAN_SUMMARY_URL')?:'','https://')&&(getenv('GUANLAN_SERVICE_TOKEN')?:'')!=='';return ['configured'=>$ready,'status'=>$ready?'summary-configured: code exchange unavailable':'unconfigured: code exchange and summary contracts unavailable'];}
 public function verifyToken(string $token):array{$base=rtrim(getenv('GUANLAN_BASE_URL')?:'','/');if(!$base||!str_starts_with($base,'https://'))throw new ApiError(503,'integration_unconfigured','需要配置可信 HTTPS 观澜地址');if(!$token||preg_match('/[\r\n]/',$token))throw new ApiError(401,'invalid_token','令牌无效');$result=$this->request('GET',$base.'/api/v1/auth/me',$token);$u=$result['data']['user']??$result['data']??null;if(!is_array($u)||(!is_string($u['id']??null)&&!is_int($u['id']??null))||($u['is_active']??true)===false||($u['status']??'active')!=='active')throw new ApiError(401,'invalid_identity','观澜身份无效');return ['id'=>'guanlan:'.$u['id'],'name'=>(string)($u['displayName']??$u['nickname']??$u['name']??'观澜学习者'),'role'=>($u['role']??'')==='admin'?'admin':'learner'];}
 public function exchangeCode(string $code,string $state,string $redirect):never{throw new ApiError(503,'integration_unconfigured','观澜尚未提供已验证的一次性授权码兑换协议');}
 public function sendSummary(array $summary):array{if(!self::status()['configured'])throw new ApiError(503,'integration_unconfigured','观澜摘要协议未明确启用');$token=getenv('GUANLAN_SERVICE_TOKEN');if(preg_match('/[\r\n]/',$token))throw new ApiError(503,'integration_configuration','服务凭证格式无效');$ctx=stream_context_create(['http'=>['method'=>'PUT','header'=>"Authorization: Bearer ".$token."\r\nContent-Type: application/json\r\nAccept: application/json\r\n",'content'=>json_encode($summary,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'timeout'=>10,'ignore_errors'=>true,'follow_location'=>0]]);$raw=@file_get_contents(getenv('GUANLAN_SUMMARY_URL'),false,$ctx);$headers=$http_response_header??[];preg_match('/\s(\d{3})\s/',$headers[0]??'',$m);$status=(int)($m[1]??503);$retryAfter=60;foreach($headers as $h)if(preg_match('/^Retry-After:\s*(\d+)/i',$h,$v))$retryAfter=(int)$v[1];$data=$raw?json_decode($raw,true):null;return ['status'=>$status,'revision'=>$data['data']['revision']??null,'retryAfter'=>$retryAfter];}
 private function request(string $method,string $url,string $token):array{$ctx=stream_context_create(['http'=>['method'=>$method,'header'=>'Authorization: Bearer '.$token."\r\nAccept: application/json\r\n",'timeout'=>8,'ignore_errors'=>true,'follow_location'=>0]]);$raw=@file_get_contents($url,false,$ctx);$status=$http_response_header[0]??'';if($raw===false||!preg_match('/ 200 /',$status))throw new ApiError(401,'identity_validation_failed','观澜会话验证失败');try{return json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(\Throwable){throw new ApiError(502,'invalid_identity_response','观澜响应无效');}}
}
