<?php
declare(strict_types=1);
namespace Mayuan;
final class ImportProgress {
 public static function validate(mixed $raw,array $c):array {
 if(!is_array($raw)||!in_array($raw['version']??null,[1,2],true))throw new ApiError(422,'invalid_import','只支持 V1/V2 备份');$out=Application::blank();$s=$raw['version']===2?($raw['state']??null):$raw;if(!is_array($s)||!is_array($s['nodes']??null)||count($s['nodes'])>count($c['nodes']))throw new ApiError(422,'invalid_import','节点格式无效');$known=array_column($c['nodes'],'id');$history=[];
 foreach($s['nodes'] as $id=>$n){if(!in_array($id,$known,true)||!is_array($n)||!is_bool($n['visited']??null)||!in_array($n['mastery']??null,['unlearned','fuzzy','mastered'],true))throw new ApiError(422,'invalid_import','导入知识点或自评无效');foreach(['updatedAt','masteryUpdatedAt'] as $field)self::time($n[$field]??0);$out['nodes'][$id]=array_intersect_key($n,Application::node())+Application::node();if($raw['version']===1){if(!is_array($n['answers']??null)||count($n['answers'])>10000)throw new ApiError(422,'invalid_import','历史答题格式无效');$correct=0;$last=null;$lastReason=null;$ordered=$n['answers'];uasort($ordered,fn($a,$b)=>($a['at']??0)<=>($b['at']??0));foreach($ordered as $aid=>$a){Application::identifier($aid);if(!is_array($a)||!is_bool($a['correct']??null)||!is_string($a['exercise']??null)||strlen($a['exercise'])>100||!is_string($a['reason']??null)||strlen($a['reason'])>1000)throw new ApiError(422,'invalid_import','历史答题字段无效');self::time($a['at']??null);$correct+=(int)$a['correct'];$last=$a['at'];$lastReason=$a['correct']?null:$a['reason'];$history[$aid]=['id'=>$aid]+$a;}if(($n['attempts']??null)!==count($ordered)||($n['correct']??null)!==$correct||($n['lastAnswered']??null)!==$last||($n['lastReason']??null)!==$lastReason)throw new ApiError(422,'invalid_import','历史统计与记录不一致');}}
 if($raw['version']===2){foreach(['attempts','historicalAnswers'] as $kind){if(!is_array($s[$kind]??null)||count($s[$kind])>10000)throw new ApiError(422,'invalid_import','历史记录集合无效');foreach($s[$kind] as $a){Application::identifier($a['id']??null);if(!is_bool($a['correct']??null)||!is_string($a['exerciseId']??($a['exercise']??null)))throw new ApiError(422,'invalid_import','历史记录无效');self::time($a['at']??null);$history[$a['id']]=$a;}}foreach(['favorites','notes','recalls'] as $kind){if(!is_array($s[$kind]??null)||count($s[$kind])>10000)throw new ApiError(422,'invalid_import','备份集合无效');foreach($s[$kind] as $v){$nid=$kind==='favorites'?$v:($v['nodeId']??null);if(!in_array($nid,$known,true))throw new ApiError(422,'invalid_import','备份引用不存在');if($kind==='notes'){Application::identifier($v['id']??null);if(!is_string($v['content']??null)||strlen($v['content'])>15000)throw new ApiError(422,'invalid_import','笔记无效');$v['updatedAt']=(int)floor(microtime(true)*1000);}if($kind==='recalls'){Application::identifier($v['id']??null);if(!in_array($v['rating']??null,['again','hard','good'],true)||!is_string($v['mode']??null))throw new ApiError(422,'invalid_import','回忆无效');self::time($v['at']??null);self::time($v['dueAt']??null,31536000000);}$out[$kind][]=$v;}}}
 $out['historicalAnswers']=array_values($history);return $out;
 }
 private static function time(mixed $v,int $future=86400000):void{if((!is_int($v)&&!is_float($v))||!is_finite((float)$v)||$v<0||$v>floor(microtime(true)*1000)+$future)throw new ApiError(422,'invalid_import','时间戳无效或来自未来');}
}
